DEBUGGING_LEVEL = 2
LT_PLAN_INTERVAL = 120
ST_PLAN_INTERVAL = 30
DR_SOLICITATION_INTERVAL = 30
CUSTOMER_SOLICITATION_INTERVAL = 30
ACCOUNTING_INTERVAL = 5
RESERVE_DISPATCH_INTERVAL = 5
ANNOUNCE_PERIOD_INTERVAL = 10